// Config plugin: release signing for android/app/build.gradle.
// android/ is not in git and is regenerated by `npx expo prebuild`, so the
// signing config must be re-applied on every prebuild — that is what this does.
// Reads keystore.properties from the PROJECT root (../ relative to android/),
// so `prebuild --clean` never deletes it. Falls back to the debug keystore
// when keystore.properties is absent (CI, other machines).
const { withAppBuildGradle } = require("expo/config-plugins");

const LOADER = `def keystorePropertiesFile = rootProject.file("../keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystorePropertiesFile.withInputStream { keystoreProperties.load(it) }
}

`;

const RELEASE_SIGNING_CONFIG = `
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }`;

function applyReleaseSigning(buildGradle) {
  // Idempotence: prebuild without --clean re-runs mods on the already-patched file.
  if (buildGradle.includes("keystore.properties")) {
    return buildGradle;
  }

  const withLoader = buildGradle.replace(/^android \{/m, LOADER + "android {");
  if (withLoader === buildGradle) {
    throw new Error("withReleaseSigning: `android {` block not found in app/build.gradle");
  }

  const withSigningConfig = withLoader.replace(
    /signingConfigs\s*\{\s*debug\s*\{[\s\S]*?\}/,
    (match) => match + RELEASE_SIGNING_CONFIG
  );
  if (withSigningConfig === withLoader) {
    throw new Error("withReleaseSigning: signingConfigs.debug block not found in app/build.gradle");
  }

  const withBuildType = withSigningConfig.replace(
    /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/,
    "$1signingConfig(keystorePropertiesFile.exists() ? signingConfigs.release : signingConfigs.debug)"
  );
  if (withBuildType === withSigningConfig) {
    throw new Error("withReleaseSigning: release buildType signingConfig not found in app/build.gradle");
  }

  return withBuildType;
}

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== "groovy") {
      throw new Error("withReleaseSigning: expected Groovy app/build.gradle");
    }
    config.modResults.contents = applyReleaseSigning(config.modResults.contents);
    return config;
  });
};
